### PR TITLE
Added option to show forked repos

### PR DESCRIPTION
**Pull request by jowilki**
Hi there! I added a "Show forked repositories" option to the widget admin panel for your plugin.  Feel free to merge if like :)

Take care

### CODE REVIEW

**Comment by fracek** [comment]
Thanks, it was something I really wanted to add but I've never found the time to do it.

Cheers

**Comment by fracek** [comment]
I almost forgot to ask you if I can add you to the contributors on wordpress.org. So is it ok if I add you on the readme.txt published on wordpress.org?

**Comment by jowilki** [comment]
Sure that'd be great.  My username is the same on wordpress, jowilki :)

**Comment by fracek** [comment]
Ok done. Thanks again!

**Pull request merged**
