### PR TITLE
javascript changes

### PR DESCRIPTION
**Pull request by cfoellmann**
I changed the javascript implementation:
proper enqueue according to wordpress codex

TODO: (maybe you @fracek can help) load js only if widget is present on page

### CODE REVIEW

**Comment by fracek** [comment]
Hello,
I will look into this over the weekend.

Thanks.

**Comment by fracek** [comment]
I have looked at it in a branch, looks good to me. I will test it in the next days and merge it.

Sorry if I can't go faster because I'm a bit busy in this period.

**Comment by fracek** [comment]
Also can you make your changes on a different branch than master? It's better for both so you don't end up with a different history than me.

(I mean for the next contributions :) )

**Comment by cfoellmann** [comment]
Sure. Will do that in the future.

No problem. Do it when you got the time. its not urgent as you can see.

**Pull request closed without merging**
