### PR TITLE
complete fix for 3.5 + German

### PR DESCRIPTION
**Pull request by cfoellmann**
see first commit.

### CODE REVIEW

**Comment by cfoellmann** [comment]
NOTE: I did not change the version number yet.

**Comment by fracek** [comment]
Looks good, thanks.

May I ask what's the nbproject/ directory?

**Comment by cfoellmann** [comment]
its the working directory of my IDE (netbeans). I am not sure how to keep it out of the repo since netbeans doesnt like it if it is outside the project itself :-(

**Comment by fracek** [comment]
What if I put it in .gitignore? Does it still work?

**Comment by cfoellmann** [comment]
Sorry I thought it was and you only saw it in the .gitignore. Put /nbproject/ in there

**Comment by fracek** [comment]
No problem.

I'm reviewing the changes right now, I'll add you to the contributors ok? What's your username on WP.org?

**Comment by cfoellmann** [comment]
Sure, thanks. My username as always cfoellmann

**Pull request merged**
